shopt -s histappend
shopt -s checkwinsize
HISTSIZE=1000
HISTFILESIZE=2000
HISTCONTROL=ignoreboth

#logging
precmd() { eval 'if [ "$(id -u)" -ne 0 ]; then echo "$(date "+%Y-%m-%d.%H:%M:%S") $(pwd) $(history -f)" >> ~/.logs/bash-history-$(date "+%Y-%m-%d").log; fi' }

source "$HOME/.profile"

for file in $HOME/.bash/*.bash; do
	source "$file"
done

for file in $HOME/.bash/*.sh; do
	source "$file"
done

bind 'set show-all-if-ambiguous on'
bind 'TAB:menu-complete'

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
	if [ -f /usr/share/bash-completion/bash_completion ]; then
		. /usr/share/bash-completion/bash_completion
	elif [ -f /etc/bash_completion ]; then
		. /etc/bash_completion
	fi
fi

#bash-completion
autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit

eval $(ssh-agent) >/dev/null

ssh-add ~/.ssh/dev >/dev/null
ssh-add ~/.ssh/homelab >/dev/null
ssh-add ~/.ssh/home >/dev/null
